### ISSUE TITLE
Merge this gem into Rails

### ISSUE THREAD

**Issue by guillaumebriday** [igorkasyanchuk/active_storage_validations#101]
Hey

This gem is really helpful and it could be very cool to see it in Rails core. 

Do you plan to open PR in rails/rails to merge it?

Thanks 🙏

**Comment by igorkasyanchuk** [comment]
Hi @guillaumebriday 
Thanks!
It was opened before and no luck with it. You can probably find the thread about it.

PS: you can check a few other gems which I've created in the past :)
