### ISSUE TITLE
Allow Procs as values for validator restrictions 

### ISSUE THREAD

**Issue by mantenie** [igorkasyanchuk/active_storage_validations#105]
Hi there!

Sometimes it is necessary to have dynamic values for validations. I have seen in some other validator gems also procs can be passed instead of integers. These are then called in the validator methods. Then it is possible for example to use ENV variables to set the dimensions or sizes.

That would be another super addition to make this extension even more useful.

**Comment by gr8bit** [comment]
Seconded! In my case, the maximum upload size depends on the logged in user.

**Comment by gr8bit** [comment]
Working on it! Stay tuned…
