### ISSUE TITLE
Rails dependency

### ISSUE THREAD

**Issue by simchikoops** [igorkasyanchuk/active_storage_validations#106]
With the dependency on Rails, and not its sub-components, it's not possible for an app that uses this gem to cut out parts of Rails to save memory. Can this be changed? Glad to come up with a PR if you can tell me what they should be (ActiveModel?).

**Comment by igorkasyanchuk** [comment]
@simchikoops interesting idea, if you can do it I'm fine, with examples and tests.

Gem could see if Rails is defined then include functionality, if not - it's fine too.
