### ISSUE TITLE
image upload size

### ISSUE THREAD

**Issue by dbbooke** [igorkasyanchuk/active_storage_validations#12]
Is there any validations for how many images a user can uploaded? For example, each post can post up to 24 images?

**Comment by reckerswartz** [comment]
Nope, never thought of that.

**Comment by reckerswartz** [comment]
@igorkasyanchuk do you want this to be handled in new validation class or i update it in size validation class?

**Comment by igorkasyanchuk** [comment]
Hi, yes, new validation class. Something like

validates ... attachments_count: { max: 15 OR min: 10  }

**Comment by ivanelrey** [comment]
Hi @igorkasyanchuk can you please review the pull request and tell me if any changes needed, thanks?

**Comment by igorkasyanchuk** [comment]
yes, already commented. very minor fix is needed not related to code
