### ISSUE TITLE
Ratio optionality not working correctly

### ISSUE THREAD

**Issue by nejdetkadir** [igorkasyanchuk/active_storage_validations#139]
![Screen Shot 2022-01-28 at 20 18 04](https://user-images.githubusercontent.com/50639655/151592520-20c7c83d-65eb-4948-b039-56aff8986d92.jpg)

rails v: 6.1.4.1
ruby v: 2.7.2

**Comment by igorkasyanchuk** [comment]
@nejdetkadir try to fork, and in dummy app, in specs use your file and make a fix. It could be a great contribution
