### ISSUE TITLE
Error : undefined method `before_attachments_post_process' for #<Class:0x000000147116c8>

### ISSUE THREAD

**Issue by farkare** [igorkasyanchuk/active_storage_validations#14]
I have added following in the model:

`validates_attachment :attachments, attached: true, content_type: { content_type: COMMON_MIME_TYPES }`

And here is what exception I get:
```
undefined method `before_attachments_post_process' for #<Class:0x000000147116c8>
Did you mean?  before_post_process
```

Am I missing something?

**Comment by reckerswartz** [comment]
Can you make sure your content type is syntax is correct?

**Comment by farkare** [comment]
Thanks @reckerswartz , it works! I missed it while migrating from paperclip to active storage.
