### ISSUE TITLE
Unknown validator: 'ContentTypeValidator' error

### ISSUE THREAD

**Issue by SamihaFansur** [igorkasyanchuk/active_storage_validations#147]
I get a Unknown validator: 'ContentTypeValidator' error on rails 6 when I try to validate my pdf files which are attached as a has_many _attached attachment.

`validates :files, content_type: {in: 'application/pdf', message: 'Please upload .pdf files only'} `

**Comment by MateoLa** [comment]
Try adding to your .gemspec file:
  spec.add_dependency "active_storage_validations"

**Comment by isabel-anastasiadis-boost** [comment]
We were getting a similar issue initially and realised we'd put the gem in the `:test` group instead of everywhere

**Comment by isabel-anastasiadis-boost** [comment]
My issue was just user error - gem wasn't added to the right group :)
