### ISSUE TITLE
uninitialized constant ActiveStorageValidations::Metadata::MiniMagick

### ISSUE THREAD

**Issue by kwent** [igorkasyanchuk/active_storage_validations#149]
Hi, this line fails when fully migrated to `vips` because we aren't loading `MiniMagick` anymore.

https://github.com/igorkasyanchuk/active_storage_validations/blob/master/lib/active_storage_validations/metadata.rb#L80

Regards

**Comment by igorkasyanchuk** [comment]
Can you make a fix, maybe we can add some dummy error class in the code, for example, DummyException (which never happen), and before rescue write something like

exception_klass = defined?(MiniMagick) ? MiniMagick::Error : DummyError

and use in `rescue exception_klass`
