### ISSUE TITLE
Release 0.9.8 (or so)

### ISSUE THREAD

**Issue by kronn** [igorkasyanchuk/active_storage_validations#155]
Since the last PR removes the need to include both `mini_magick` AND `vips` in the `Gemfile`, it is an important release for me. For development, I can (and do) use the gem as a git-dependency. For production-deployments, I would prefer a gem available from rubygems.org.

Could you make a new release of your gem?

**Comment by igorkasyanchuk** [comment]
Released, sorry for a delay

**Comment by kronn** [comment]
Thank you very much
