### ISSUE TITLE
Push release tags

### ISSUE THREAD

**Issue by tagliala** [igorkasyanchuk/active_storage_validations#156]
Hi, is it possible to push release tags to GitHub?

**Comment by igorkasyanchuk** [comment]
Hi, why is it needed?

**Comment by tagliala** [comment]
Hi, thanks for the prompt response and the new release

Releases tags are very useful to browse the source code at the exact commit of the release, in example I would like to check source code of 0.9.7, and I could have done here: https://github.com/igorkasyanchuk/active_storage_validations/tags

I will use rails itself as example: https://github.com/rails/rails/tags

**Comment by igorkasyanchuk** [comment]
I'll try to do, created for current 0.9.8. Next time will try to do for the next release
