### ISSUE TITLE
Aspect Ratio generally includes a ':', not a 'x'

### ISSUE THREAD

**Issue by yarmiganosca** [igorkasyanchuk/active_storage_validations#160]
Aspect ratios are generally given as 16:9 or 4:3, not 16x9, at least in my experience (maybe this differs between language contexts). This results in the error messages this gem produces being a little confusing.

**Comment by igorkasyanchuk** [comment]
I'm fine if you can create a PR with this fix. Should be easy to change.

**Comment by yarmiganosca** [comment]
I should be able to put one together tomorrow.
