### ISSUE TITLE
Conditional validation not working

### ISSUE THREAD

**Issue by kukicola** [igorkasyanchuk/active_storage_validations#166]
Hello
Version 1.0.0 broke my validation:

```
validates :avatar, content_type: ALLOWED_CONTENT_TYPES, size: { less_than: 10.megabytes }, if: -> { attachment_changes['avatar'] }
```

```
    Failure/Error: validates :avatar, content_type: ALLOWED_CONTENT_TYPES, size: { less_than: 10.megabytes }, if: -> { attachment_changes['avatar'] }
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

after removing `if` it works correctly. Maybe it's connected to https://github.com/igorkasyanchuk/active_storage_validations/pull/135/files ?

**Comment by igorkasyanchuk** [comment]
@gr8bit, @StefSchenkelaars is it something that you can look?

@kukicola if possible maybe you can fork and create a fix?

**Comment by gr8bit** [comment]
I will look into it. From a first guess, I think `if` might be picked up in the proc unfolding and get the record passed inside which the proc doesn't want.

**Comment by gr8bit** [comment]
@igorkasyanchuk fixed and added tests for the case. :)
