### ISSUE TITLE
Size `less_than` depending content type

### ISSUE THREAD

**Issue by GesJeremie** [igorkasyanchuk/active_storage_validations#177]
First, thanks for the work done on this gem, it's a pleasure to use :)

I was wondering if it was possible to set different size constraints depending the content type, I started to investigate a solution with a proc, but it failed short:

```ruby
class Post < ApplicationRecord
  # ...
  validates :picture,
    content_type: ['image/png', 'image/jpeg', 'image/gif'],
    size: { less_than: -> (record) { true ? 15.megabytes : 5.megabytes} }
end
```

Error returned: `comparison of Integer with Proc failed`.

**Comment by igorkasyanchuk** [comment]
@shido76 @GesJeremie can you create a PR with a failed spec? Could be useful and helpful for us to create a fix.

**Comment by Mth0158** [comment]
Hi,
I have created a PR that solves this issue [here](https://github.com/igorkasyanchuk/active_storage_validations/pull/183) 😀

**Comment by Mth0158** [comment]
@shido76 @GesJeremie can you create a PR with a failed spec and that fixes this issue ? or give a bit more context to this issue?

**Comment by Mth0158** [comment]
@shido76 @GesJeremie I will investigate this issue shortly.

My first guess is that if you are using `has_one_attached`, you might be able to do it using the below (untested) code:
```ruby
class Post < ApplicationRecord
  # ...
  validates :picture,
    content_type: ['image/png', 'image/jpeg', 'image/gif'],
    size: { less_than: -> (record) { record.picture.blob.content_type == :png ? 15.megabytes : 5.megabytes} }
end
```
I'll work a bit on it in the following days, I'll let you know

**Comment by Mth0158** [comment]
@shido76 @GesJeremie I have investigated this issue, it works fine on my side.
It is working with the below code:
```ruby
class Post < ApplicationRecord
  # ...
  validates :picture,
    content_type: ['image/png', 'image/jpeg', 'image/gif'],
    size: { less_than: -> (record) { record.picture.blob.content_type == "image/png" ? 15.megabytes : 5.megabytes} }
end
```

I have added a test to ensure no future regression on this use case, let me know if you still have issues, otherwise I'll close this issue in the next days
