### ISSUE TITLE
Dimension of videos are not validated

### ISSUE THREAD

**Issue by mikefranken** [igorkasyanchuk/active_storage_validations#190]
I get `Skipping image analysis because ImageMagick or Vips doesn't support the file`, and the `Meta` class used for validation just seems to support images, not video. 

Or am I missing something?

**Comment by igorkasyanchuk** [comment]
I was never trying to check how if works or not with video, but you saying it doesn't work - than we need a PR with a fix :) 

do you think you can check this and implement?

**Comment by mikefranken** [comment]
sure, see https://github.com/igorkasyanchuk/active_storage_validations/pull/191

**Comment by igorkasyanchuk** [comment]
here is a quick PR to check the logic https://github.com/igorkasyanchuk/active_storage_validations/pull/192/files
Your PR is too early to merge. I see that validation works, so I would just ask to spend more time.

**Comment by Mth0158** [comment]
@igorkasyanchuk do you need help on this one? I could dive into possible solutions

**Comment by Mth0158** [comment]
Hi,
I am closing this issue. It will be handled with https://github.com/igorkasyanchuk/active_storage_validations/issues/255, that is going to be released with gem v2 (before year's end I think :))
