### ISSUE TITLE
New validation option to check that file extension matches mime type

### ISSUE THREAD

**Issue by tagliala** [igorkasyanchuk/active_storage_validations#195]
Hi,

I would like to propose a new validation that checks if the extension matches the actual content type of the document. This should help to prevent upload of a `.pdf` which is actually a `.docx`

I don't know a good name for this validation, or if it should be an option of `content_type`, like `match_extension: true`

I can work on a PR if you are interested

**Comment by igorkasyanchuk** [comment]
Let's wait a few days for comment's. Could be useful.

**Comment by valscion** [comment]
This sounds like content type spoofing validation. Similar to what `file_validators` has: require "rails"

%w(
  active_record/railtie
  active_storage/engine
  action_controller/railtie
  action_view/railtie
  action_mailer/railtie
  active_job/railtie
  action_cable/engine
  action_mailbox/engine
  action_text/engine
  rails/test_unit/railtie
  sprockets/railtie
).each do |railtie|
  begin
    require railtie
  rescue LoadError
  end
end

**Comment by lavaturtle** [comment]
This sounds like a good idea to me too.

**Comment by tagliala** [comment]
> NOTE: Also starting at version 4.0.0, Paperclip has another validation that cannot be turned off. This validation will prevent content type spoofing. That is, uploading a PHP document (for example) as part of the EXIF tags of a well-formed JPEG. This check is limited to the media type (the first part of the MIME type, so, 'text' in text/plain). This will prevent HTML documents from being uploaded as JPEGs, but will not prevent GIFs from being uploaded with a .jpg extension. This validation will only add validation errors to the form. It will not cause errors to be raised.

this is also interesting

**Comment by Mth0158** [comment]
Yes that looks like a really good addition to the gem, I'll work on it in the coming days, let me know if you want to help :)

**Comment by Mth0158** [comment]
Hi everyone! @tagliala, @valscion, @lavaturtle

I finally finished the PR about this feature, it was a not so easy task. I had to try several approaches to find the most suitable.
If anyone of you is interested in having a quick look at the PR before we merge it it would be appreciated :)

[https://github.com/igorkasyanchuk/active_storage_validations/pull/256](https://github.com/igorkasyanchuk/active_storage_validations/pull/256)

**Comment by tagliala** [comment]
Hi, thanks for your hard work on the PR implementing this

There are a lot of changes, I would start backporting as many non-breaking changes as possible to keep the PR as small as possible

Also the change replacing OpenStruct with Struct is interesting (if it is only used there)

Probably the updates to the CI are a good candidate, even if that will mean stop testing against Marcel 0.3

**Comment by tagliala** [comment]
At the moment I'm using this custom code

```rb
# frozen_string_literal: true

class FileExtensionValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    return unless value&.attached?
    return if value.content_type == Marcel::MimeType.for(extension: value.filename.extension)

    # Workaround for legacy Outlook emails
    # .msg are not detected as application/vnd.ms-outlook mime types, so users
    # are not able to upload msg emails exported by outlook desktop (the web version exports emails as .eml)
    # The problem is the front-end filter with [accept attribute](https://caniuse.com/input-file-accept)
    # A workaround would be to send .msg together with mime types on the front-end when
    # application/vnd.ms-outlook mime type is allowed
    return if value.content_type == 'application/x-ole-storage' && value.filename.extension == 'msg'

    record.errors.add(attribute, :bad_file_extension, **options)
  end
end
```

There are also some other edge cases with some files being detected as plain text, but I cannot recall them at the moment

**Comment by Mth0158** [comment]
Well, the change might appear as big, but it mostly is concentrated in updating the gemfiles (Rails 6.1.3 -> 6.1.4, marcel >= 1.0.3), adding the `content_type_spoof_detector.rb` file, updating the `content_type_validator.rb ` and adding the tests.

The major change, that is breaking, is the default spoofing protection, as discussed on the PR, we will release a minor version with the spoofing protection not activated by default, and then a major one with it activated by default.

We could still support Marcel =< 0.3, but I think it's the opportunity to move forward the Rails versions we support. Rails 6.1 will soon EOL (probably with Rails 8 in Septembre/October), so moving forward from 6.1.3 to 6.1.4 does not seem like a big problem to me (but I might overstep?).
