### ISSUE TITLE
Rails default validation options missing from errors

### ISSUE THREAD

**Issue by Benoit-Baumann** [igorkasyanchuk/active_storage_validations#196]
Hello,

I noticed that the [Rails' validation options](https://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validates) (:if, :unless, :on, :allow_nil, :allow_blank, and :strict) are not added to the generated errors unlike Rails does with its own validators:

```ruby
class User < ApplicationRecord
  has_one_attached :avatar

  validates :avatar, attached: true, on: :foo
  validates :email, presence: true, on: :bar
end

user = User.new

user.valid?
=> true

user.valid?(:bar)
=> false

user.errors
=> #<ActiveModel::Errors [#<ActiveModel::Error attribute=email, type=blank, options={:on=>:bar}>]> # 'on' option is present

user.valid?(:foo)
=> false

user.errors
=> #<ActiveModel::Errors [#<ActiveModel::Error attribute=avatar, type=blank, options={}>]> # 'on'  option is missing !
```

Is there any reason why these options are not added to the errors ? If not, it would be awesome to have them.

Thanks for the gem BTW 💎

**Comment by Mth0158** [comment]
Hi @Benoit-Baumann!
Nice to meet you, we never had a chance to meet in Lyon, but I heard of you from StudioHB!
I've investigated your issue, I think it's a nice (and easy) addition to the gem. I'll make a PR on that matter in the following days/weeks.
See you
