### ISSUE TITLE
Open PR on Rails

### ISSUE THREAD

**Issue by tleneveu** [igorkasyanchuk/active_storage_validations#2]
@igorkasyanchuk Do you plan to open a PR on Rails ?

I can help if needed.

**Comment by igorkasyanchuk** [comment]
yes, but I'll let you know if I need help. A very interesting task, plan to start very soon.
Already created an issue https://github.com/rails/rails/issues/33741

**Comment by tleneveu** [comment]
@igorkasyanchuk 🆙

**Comment by tleneveu** [comment]
@reckerswartz has create a PR 

https://github.com/rails/rails/pull/34842
