### ISSUE TITLE
ActiveRecord::Base subclass requirement

### ISSUE THREAD

**Issue by dvodvo** [igorkasyanchuk/active_storage_validations#207]
An multi-tenant application has various classes relying on ActiveStorage (tenant is defined by class Shop). 
Validation values are stored in a db table for each class, by tenant.

In the basic set-up, before validations, 
```ruby
class Document < ApplicationRecord
  
  belongs_to :individual, optional: true
  belongs_to :union, optional: true

  validate  :at_least_one_identifier
  has_one_attached :file
#  validates :file, limit: { max: -> (record) { record.shop.document_validation.size_less_than }, message: t('is too large') }
  
  def at_least_one_identifier
    if [self.individual_id, self.union_id].reject(&:blank?).size == 0
      errors[:base] << (I18n.t('picture.one_identifier'))
    end
  end
end
```
Creating an attached file runs as expected and the view renders.  However the proc declaration for tha validation returns the error  `Rails couldn't find a valid model for Document association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.`

The class structures are:
```ruby
class Individual < ApplicationRecord
  belongs_to :shop

[...]
class Union < ApplicationRecord
  belongs_to :shop

[...]
class Shop < ApplicationRecord
  has_one    :document_validation

[...]
class DocumentValidation < ApplicationRecord
  belongs_to :shop
```
The latter category stores values for validating documents of the shop's class.

Given that document can belong to either Individual or Union, also attempted was:
```ruby
  validates :file, limit: { max: -> (record) { record.individual.shop.document_validation.size_less_than }, message: t('is too large') }
```
but leading to the same error.

What I fail to understand is how the attached object can be created with the rails-generated scaffolding, but the validation cannot run (and obviously how to get out of the conundrum).

**Comment by Mth0158** [comment]
Hi @dvodvo 
I guess it's more a Rails / ActiveRecord related error than a ActiveStorageValidations error. Here you have an issue associating your models. I'll close this issue, let me know if we need to reopen it.
