### ISSUE TITLE
Matchers - Add `limit_validator`matcher

### ISSUE THREAD

**Issue by Mth0158** [igorkasyanchuk/active_storage_validations#211]
Some validators do not have their matcher, it should be implemented.

This issue is for `limit_validator` matcher

**Comment by chahmedejaz** [comment]
Hey @Mth0158 - I'd love to work on this issue, can you please assign it to me? Thanks.

**Comment by Mth0158** [comment]
Hi @chahmedejaz! Thanks for your message, I have just assigned the ticket to you.
Just to let you know, it's better if you wait a few days to start this one, a lot of things will be refactored on the matcher part once #206 is merged :)

**Comment by chahmedejaz** [comment]
> Hi @chahmedejaz! Thanks for your message, I have just assigned the ticket to you. Just to let you know, it's better if you wait a few days to start this one, a lot of things will be refactored on the matcher part once #206 is merged :)

Sure, thanks for the heads up :)

**Comment by Mth0158** [comment]
@chahmedejaz it's been merged if you want to start this one

**Comment by chahmedejaz** [comment]
Thanks for letting me know @Mth0158. I'll pick this up now :)

**Comment by Mth0158** [comment]
Hi @chahmedejaz,
Any update on this PR?
FYI, the `AspectRatioValidatorMatcher` has already been developed by #153, sorry for that if you've coded it

**Comment by chahmedejaz** [comment]
> Hi @chahmedejaz, Any update on this PR? FYI, the `AspectRatioValidatorMatcher` has already been developed by #153, sorry for that if you've coded it

Hey @Mth0158 - I'm working on it. Sorry I got overbooked with issues. I'll submit the PR soon, thanks for the update. 👍

**Comment by Mth0158** [comment]
Done with #263
