### ISSUE TITLE
Add support for multiple aspect ratios

### ISSUE THREAD

**Issue by Mth0158** [igorkasyanchuk/active_storage_validations#230]
Like content_type, we should be able to support multiple aspect ratios.

Possible to get inspiration from this fork: https://github.com/igorkasyanchuk/active_storage_validations/compare/master...nejdetkadir:active_storage_validations:master. But not too much because they modified the :with option, we would rather like something with :in like content_type validator does.

Do not forget to add tests to your validator update + update the associated matcher

Please notify the fork owner so he/she can update its gemfile

**Comment by mohammednasser-32** [comment]
Hello @Mth0158 , just checking before jumping in since this seems to be open for a while :sweat_smile: can I work on this?

**Comment by Mth0158** [comment]
Hi @mohammednasser-32 
Yes, you can jump on it, let me know if you need any assistance:)
