### ISSUE TITLE
.ino files seem to be ignored

### ISSUE THREAD

**Issue by vnguyen13** [igorkasyanchuk/active_storage_validations#239]
Hi there,

I'm running on rails 6.1, and ruby 2.7.1p83. 

I'm trying to handle validation for uploads that are .ino files. They are programs that come from the Arduino software. I have tried to do the following:

`validates :upload, attached: true, content_type: [:xlsx, :csv, :ino]`

However, it seems to ignore it. This is what my console shows:

`Started POST "/client_api/v1/mixed_medias" for 127.0.0.1 at 2024-01-18 14:53:48 -0500
14:53:50 web.1               | Processing by ClientApi::V1::MixedMediasController#create as HTML
14:53:50 web.1               |   Parameters: {"mixed_media"=>{"upload"=>#<ActionDispatch::Http::UploadedFile:0x000000012a264730 @tempfile=#<Tempfile:/var/folders/mk/4vc8w_651117z_jywvq6kf3r0000gp/T/RackMultipart20240118-99810-1ev04ze.ino>, @original_filename="maze.ino", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"mixed_media[upload]\"; filename=\"maze.ino\"\r\nContent-Type: application/octet-stream\r\n">, "description"=>"jjjj"}, "requirement_id"=>"2098"}`

It's showing as an "application/octet-stream". 

I did try to add 'application/octet-stream' to the list too, but it still doesn't allow it:
`validates :upload, attached: true, content_type: [:xlsx, :csv, :ino, 'application/octet-stream']`

Any help would be appreciated. Thank you!

**Comment by igorkasyanchuk** [comment]
Hello, can you try to download source of the gem, connect it locally in your app and use a debugger, and see why it doesn't work? It would be great if you can make a fix and send PR with it

**Comment by Mth0158** [comment]
Hi,
The defined content_types used by the gem are the ones referenced by `Marcel` gem (here: https://github.com/rails/marcel/blob/main/lib/marcel/tables.rb)
I couldn't see something like .ino files though, so I would suggest that you add this mime type to the Marcel gem by using:
```ruby
Marcel::MimeType.extend "text/custom", extensions: %w( customtxt )
Marcel::MimeType.for name: "file.customtxt"
#  => "text/custom"
```
Then you could use the `:ino` with the content_type validator, as for using `'application/octet-stream'`it will not work because we identify it as a bad mime type (cf code here -> https://github.com/igorkasyanchuk/active_storage_validations/blob/18bde2d24f507511237cc7b81706b7a218e721d0/lib/active_storage_validations/content_type_validator.rb#L88)

**Comment by vnguyen13** [comment]
> Hi, The defined content_types used by the gem are the ones referenced by `Marcel` gem (here: https://github.com/rails/marcel/blob/main/lib/marcel/tables.rb) I couldn't see something like .ino files though, so I would suggest that you add this mime type to the Marcel gem by using:
> 
> ```ruby
> Marcel::MimeType.extend "text/custom", extensions: %w( customtxt )
> Marcel::MimeType.for name: "file.customtxt"
> #  => "text/custom"
> ```
> 
> Then, I think that, since Rails uses Marcel behind the scenes to identify the uploaded file content_type, it should be able to identify your file as `:ino` type (not 100% sure about this assumption, try and tell us!)
> 
> Then, if it works, you could use the `:ino` with the content_type validator, as for using `'application/octet-stream'`it will not work because we identify it as a bad mime type (cf code here ->
> 
> https://github.com/igorkasyanchuk/active_storage_validations/blob/18bde2d24f507511237cc7b81706b7a218e721d0/lib/active_storage_validations/content_type_validator.rb#L88-L95
> 
> )

Thanks for the direction! Where should I put that code? I tried putting it in a "mime_types.rb" file in initializers, and put:

`Marcel::MimeType.extend "text/ino", extensions: %w( ino )`

I wasn't sure if I needed your second line because it seems like it's looking for a specific filename, whereas the user could upload any .ino file. Sadly, this didn't fix the issue. Though I may be doing it wrong.

**Comment by Mth0158** [comment]
@vnguyen13 great news! I'll add a line in the readme to illustrate this case. Thank you for the investigation
