### ISSUE TITLE
Improvements, add dimension validation able to avoid malicious images

### ISSUE THREAD

**Issue by aryrabelo** [igorkasyanchuk/active_storage_validations#24]
I believe that I'm able to add dimension validations, using FastImage gem that can avoid malicious images such as pointed out here: https://github.com/fuzzdb-project/fuzzdb/tree/master/attack/file-upload/malicious-images

Do you think this is a valid contribution?

**Comment by igorkasyanchuk** [comment]
This could be useful. To have validation like minimum, maximum dimension size. For example I personally could use it. Try to create PR with initial code and see if you need help

**Comment by phlegx** [comment]
I give it a try! I create a PR on success. :v:
