### ISSUE TITLE
validate_aspect_ratio_of show wrong number of arguments (given 1, expected 2)

### ISSUE THREAD

**Issue by sbrocos** [igorkasyanchuk/active_storage_validations#246]
I have define this in mi model:
```
  validates :cover, attached: true,
                    content_type: %i[png jpeg],
                    aspect_ratio: :square,
                    dimension: { width: { min: 400, max: 1200 } }
```

And in the Rspec
`it { is_expected.to validate_aspect_ratio_of(:cover).allowing(:square) }`

and obtain this the execute the test:
<img width="1049" alt="Captura de pantalla 2024-04-03 a las 16 33 14" src="https://github.com/igorkasyanchuk/active_storage_validations/assets/1169745/fff8169c-fee3-4128-bb7c-bcb64e756081">

I show the code, and I don't understand what it's the problem with this validation.

Thanks for your work

**Comment by osmarluz** [comment]
@sbrocos there's an issue with the initilization of the matcher class `ActiveStorageValidations::Matchers::AspectRatioValidatorMatcher`. As a workaround you can do this:

```ruby
is_expected.to ActiveStorageValidations::Matchers::AspectRatioValidatorMatcher.new(:cover).allowing(:square)
```

Hope this helps! o/

**Comment by Mth0158** [comment]
Hi @sbrocos,
I'll have a look at it, seems like an easy bug to fix.

**Comment by Mth0158** [comment]
Hi @sbrocos & @osmarluz,
Thanks for the bug report, it has been corrected, it should be available in the new gem version soon :)
