### ISSUE TITLE
Content type validation simply not working

### ISSUE THREAD

**Issue by jasonperrone** [igorkasyanchuk/active_storage_validations#26]
```
class Accessory < ApplicationRecord
  has_one_attached :image
  validates :image, attached: true, content_type: { in: 'image/jpg', message:  'Picture must be jpg'}
end

rails console

a = Accessory.find(1)
a.image.attach(io: File.open('/home/jason/Documents/Affidavit.pdf'), filename: 'test', content_type: 'application/pdf')
```

No validation error is given and active storage records are created.

**Comment by jasonperrone** [comment]
I think the problem here is that active storage upload is done even if validation fails. Is that as expected?

**Comment by igorkasyanchuk** [comment]
not sure, but maybe I've seen some post about this bug in active storage, which should be fixed in rails 6.

**Comment by jasonperrone** [comment]
Ok. It's not a problem for me right now, I can wait till 6. Thanks!
