### ISSUE TITLE
'Aspect Ratio' validation

### ISSUE THREAD

**Issue by connorshea** [igorkasyanchuk/active_storage_validations#27]
Related to #24 and #25, I'd like to be able to validate the aspect ratio of an image. For example, I want user avatars to be square, so the height and width have to match. I don't really care what size the image is in exact pixels (so, e.g. `dimensions: { width: 200, height: 200 }` wouldn't work for me).

For me, a simple `is_square` validation would work, like so:

```ruby
validates :image, aspect_ratio: { :is_square }
```

I imagine you could alternatively have something like this, if we want to support more than just square images:

```ruby
# Height and width must match.
validates :image, aspect_ratio: { :square }
# Width must be greater than height.
validates :image, aspect_ratio: { :landscape }
# Height must be greater than width.
validates :image, aspect_ratio: { :portrait }
```

Or potentially even have exact ratios, e.g. `16:9` or `16:10` for desktop wallpapers.

Thoughts?

**Comment by reckerswartz** [comment]
@connorshea ratio will be much flexible option from range  1:1  to n:m, rather than using limited alias, which also not good way to determine perfect need.

**Comment by igorkasyanchuk** [comment]
I think this is could be very useful feature and I think 

aspect_ratio: square/landscape/portrait/16_x_9/3_x_4/1_x_1/etc.. are all valid, some of them will be a synonims for other.

@connorshea, @reckerswartz  do you think you can implement it?

**Comment by igorkasyanchuk** [comment]
Work in progress:

https://github.com/igorkasyanchuk/active_storage_validations/pull/34

**Comment by igorkasyanchuk** [comment]
added.
now in version 0.8.0 and master
