### ISSUE TITLE
[SpoofingDetection] Issue

### ISSUE THREAD

**Issue by Mth0158** [igorkasyanchuk/active_storage_validations#275]
I've tried the new spoofing detection feature. Very nice work.

Unfortunately, I get an exception:

```
      NoMethodError:
        undefined method `attachable' for nil
```

when trying to update a record after creation. It's due to this line:

`@record.attachment_changes[@attribute.to_s].attachable`

After the first record save, when calling `update!` on the same record for example, `@record.attachment_changes` is empty (`{}`).

_Originally posted by @MaksJS in https://github.com/igorkasyanchuk/active_storage_validations/issues/256#issuecomment-2425184130_

**Comment by Mth0158** [comment]
@MaksJS thanks for reporting the issue,
I'll investigate it this week to fix it shortly :)

**Comment by MaksJS** [comment]
@Mth0158 Thanks for your reactivity 👍

**Comment by Mth0158** [comment]
FYI @MaksJS I am making the PR. It takes a bit longer than expected, but it should arrive soon ;)
