### ISSUE TITLE
Video content types not working since 1.3.1

### ISSUE THREAD

**Issue by iainbeeston** [igorkasyanchuk/active_storage_validations#293]
Since 1.3.1 I've had issues with validating the content type of videos (I originally mentioned this in #280 but that issue has been closed). I haven't been able to tell what is causing the issue but I have been able to reproduce in a test: [cf953b31fbb5f053234852fe2b827d767abed80c](https://github.com/igorkasyanchuk/active_storage_validations/compare/master...iainbeeston:active_storage_validations:validate-video-attachments). The test passes on 1.3.0 and earlier, but fails on 1.3.1+ (including 1.3.3) with the validation error: `"Video has an invalid content type"`

**Comment by iainbeeston** [comment]
I assume this must be related to #292 and #282

**Comment by Mth0158** [comment]
Hi @iainbeeston,
Could you provide a bit more context? Like the model validations + the way you are attaching the file? It'll help solve the issue

**Comment by Mth0158** [comment]
Incoming bugfix release in the next hours/tomorrow to definitely fix this issue => we do not perform the extension vs content_type that causes this mess. Sorry for the unexpected breaking changes, it should have been tested more.

Let us know if you have any features idea to enhance the gem by the way :)

**Comment by iainbeeston** [comment]
@Mth0158 Great, thanks. Could you include the test from https://github.com/igorkasyanchuk/active_storage_validations/compare/master...iainbeeston:active_storage_validations:validate-video-attachments in your fix? That reproduces the issue I'm seeing and should help prevent it happening again

**Comment by Mth0158** [comment]
The fix has been released, upgrade to [1.3.4](https://github.com/igorkasyanchuk/active_storage_validations/releases/tag/1.3.4) to fix the issue :)

**Comment by iainbeeston** [comment]
@Mth0158 It works for me! Thank you so much for all the work over the last few days to fix bugs
