### ISSUE TITLE
Typo in Readme in test matcher descriptions

### ISSUE THREAD

**Issue by D4uS1** [igorkasyanchuk/active_storage_validations#298]
Hey guys,

i just realized that there is a typo in the Readme file in the section for the test matchers.
The line [here](https://github.com/igorkasyanchuk/active_storage_validations/blob/af5074140aa533e50cbbb3be4d93f08edc87581a/README.md?plain=1#L357) says it is called __validate_limit_of__, but as you can see in the [source code](https://github.com/igorkasyanchuk/active_storage_validations/blob/af5074140aa533e50cbbb3be4d93f08edc87581a/lib/active_storage_validations/matchers/limit_validator_matcher.rb#L13) it must be called __validate_limits_of__ .

**Comment by Mth0158** [comment]
Hi @D4uS1,
Thanks for reporting the issue, could you make a PR about it so we can fix this? :)

**Comment by D4uS1** [comment]
#300

**Comment by Mth0158** [comment]
Fixed with #300, thanks @D4uS1
