### ISSUE TITLE
Rails 5.2: delete attachment if it's not valid

### ISSUE THREAD

**Issue by pjmartorell** [igorkasyanchuk/active_storage_validations#30]
Hi! as you already know, in Rails 5.2 validations on ActiveStorage attachments are useless since they are saved as soon as they are assigned to a model. Then, it would be possible to add a custom behaviour for Rails 5.2 that deletes the attachment if the attachment is not valid?
If you have any idea that works outside of this gem it would be really appreciated as well :roll_eyes: 

The only shitty solution I came up with is:

```ruby
  has_many_attached :files

  validates :files, content_type: { in: ALLOWED_CONTENT_TYPES, message: 'is not a valid file' }
  after_validation :delete_invalid_attachments

  private

  def delete_invalid_attachments
    files.last.destroy if errors.include?(:files)
  end
```

But this would work only with a `has_one_attached` because you know beforehand that just one attachment could be invalid. With `has_many_attached` it gets worse since I don't know how many files were attached and I'm just deleting the latest one :hankey:

**Comment by igorkasyanchuk** [comment]
in rails 6 it's fixed I guess

but for rails 5
try this approach (should work for both one and many attached files, but didn't try)

Maybe we can create some helper to do it automatically, so I'm looking for volunteers :)

```
def delete_invalid_attachments
   return unless errors.include?(:files)
   files_to_delete = Array.wrap(self.files)
   files_to_delete.each(&:destroy)
end
```

**Comment by pjmartorell** [comment]
Thanks for your reply, but your solution is destroying all files and it should only destroy the ones added in the current request or at least only delete the ones that are invalid, but not all of them. The Array.wrap is unnecessary I think, because `files` it's already an Array of attachments.

**Comment by pjmartorell** [comment]
I think the best solution would be to somehow add validations directly to `ActiveStorage:: Attachment` itself, maybe including a `Concern` or something like that. This will ensure that no invalid attachments are created. But this will make all attachments to have the same validations, anyway I think something similar to this would do the trick.

**Comment by pjmartorell** [comment]
Finally I monkey-patched ActiveStorage::Attachment to include validations:

`config/initializers/active_storage_attachment_validations.rb`:
```ruby
Rails.configuration.to_prepare do
  ActiveStorage::Attachment.class_eval do
    ALLOWED_CONTENT_TYPES = %w[image/png image/jpg image/jpeg].freeze

    validates :content_type, content_type: { in: ALLOWED_CONTENT_TYPES, message: 'of attached files is not valid' }
  end
end
```
`app/validators/content_type_validator.rb`:
```ruby
class ContentTypeValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, _value)
    return true if types.empty?
    return true if content_type_valid?(record)

    errors_options = { authorized_types: types.join(', ') }
    errors_options[:message] = options[:message] if options[:message].present?
    errors_options[:content_type] = record.blob&.content_type
    record.errors.add(attribute, :content_type_invalid, errors_options)
  end

  private

  def content_type_valid?(record)
    record.blob&.content_type.in?(types)
  end

  def types
    Array.wrap(options[:with]) + Array.wrap(options[:in])
  end
end
```

Due to the implementation of the `attach` method in Rails 5:
```ruby
    def attach(*attachables)
      attachables.flatten.collect do |attachable|
        if record.new_record?
          attachments.build(record: record, blob: create_blob_from(attachable))
        else
          attachments.create!(record: record, blob: create_blob_from(attachable))
        end
      end
    end
```
The `create!` method raises an `ActiveRecord::RecordInvalid` exception when validations fail, but it just needs to be rescued and that's all. I hope it helps someone 🙄

**Comment by igorkasyanchuk** [comment]
This gem doesn't patch Rails and has no control on this behavior.
In Rails 6 this issue is fixed and use this version of gem:

gem 'active_storage_validations', github: 'igorkasyanchuk/active_storage_validations', branch: 'rails.6.rc1.fix'
