### ISSUE TITLE
`require': cannot load such file -- mini_magick

### ISSUE THREAD

**Issue by prettyGoo** [igorkasyanchuk/active_storage_validations#32]
> Ruby: 2.5.3
> Rails: 6.0.0rc1
> This gem: 0.7.1

I tried to add some validations to the image field attached via active-storage. However, when I launch my rails server, I get next error

```
5: from /Users/abc/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/active_storage_validations-0.7.1/lib/active_storage_validations/dimension_validator.rb:8:in `initialize'
          4: from /Users/abc/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
          3: from /Users/abc/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
          2: from /Users/abc/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
          1: from /Users/abc/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.8/lib/zeitwerk/kernel.rb:23:in `require'
/Users/abc/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.8/lib/zeitwerk/kernel.rb:23:in `require': cannot load such file -- mini_magick (LoadError)
```

As I see **_mini_magic_** comes as dev-dependency for this gem, but it's absent in my _**Gemfile.lock**_. So my question is **_mini_magic_** obligatory to use with this gem for image validation? My app uses **_active_storage + imgproxy_** for image handling

**Comment by igorkasyanchuk** [comment]
from what I see it's needed for dimension validations (but it's anyway doesn't work with Rails 6 RC at least now), so PR is needed

**Comment by igorkasyanchuk** [comment]
try this PR => https://github.com/igorkasyanchuk/active_storage_validations/pull/33

**Comment by igorkasyanchuk** [comment]
check this branch: https://github.com/igorkasyanchuk/active_storage_validations/tree/rails.6.rc1.fix if it works

**Comment by igorkasyanchuk** [comment]
OK, in Readme it says to add this dependency if you are using dimension validator. Mini_magic gem is optional since it's only needed for this type of validation.
