### ISSUE TITLE
When doing validating against spoofing `ActiveStorageValidations::ASVAttachable#attachable_io` calls `read` without rewinding

### ISSUE THREAD

**Issue by sakif-imtiaz** [igorkasyanchuk/active_storage_validations#320]
I have some code that goes:
```
message.attachments.attach(io: File.open('path/to/file'), filename: filename, content_type: media_content_type)
```
and ActiveStorage thinks it's empty down the road, so it fails to attach

my workaround in `Message` seems to work:
```
  validates :attachments, PermittedContentTypes.permissive
  after_validation :rewind_new_attachments

  def rewind_new_attachments
    return if attachment_changes.blank?

    attachment_changes['attachments']&.attachables&.each { _1[:io].try(:rewind) }
  end
```

If I `#rewind` after `#read` here, it works. There are a few of other cases in `#attachable_io` here that `#read` too though, so maybe this applies to those as well?
```
module ActiveStorageValidations
  module ASVAttachable
  ...
    def attachable_io(attachable)
      case attachable
      ...
      when Hash
        attachable[:io].read
      end
      ...
    end
  ...
end
```

**Comment by Mth0158** [comment]
Hi @sakif-imtiaz,
By any chance, were you using the `spoofing_protection: true` option in your `content_type` validator?
Could you provide your model validation your the targeted attributes?

**Comment by Mth0158** [comment]
Will be available in a coming `1.3.5` release this week.

**Comment by Mth0158** [comment]
@sakif-imtiaz Released is up, let me know if you still have this issue :)

**Comment by sakif-imtiaz** [comment]
It works, thank you so much! 

Just so that the info is here, I was using spoofing protection, so it looked like this:
`validates :attachments, content_type: { with: %r{\Aimage/.*\z}, spoofing_protection: true }`
