### ISSUE TITLE
All validations don't work with Rails 6 in tests

### ISSUE THREAD

**Issue by falseresync** [igorkasyanchuk/active_storage_validations#39]
My stack:
- Rails 6
- RSpec
- This gem

My model code:
```ruby
class User < ApplicationRecord
  has_one_attached :avatar
  validates :avatar,
    size: { less_than: 1.megabyte },
    content_type: [ :png, :jpeg, :gif ],
    aspect_ratio: :square,
    dimension: { 
      width: { in: 16..256 },
      height: { in: 16..256 }
    }
end
```

My spec code:
```ruby
describe '#avatar' do
  it 'should allow attaching a picture' do
    subject.avatar.attach(
      io: File.open(Rails.root.join('spec/fixtures/files/dummy_image.jpg')), 
      filename: 'attachment.jpg', 
      content_type: 'image/jpg')
    expect(subject.avatar).to be_attached
  end
  it 'should not allow attaching garbage' do
    subject.avatar.attach(
      io: File.open(Rails.root.join('spec/fixtures/files/example_mod.jar')), 
      filename: 'attachment.jpg', 
      content_type: 'image/jpg')
    expect(subject.avatar).not_to be_attached
  end
end
```
First example passes with any file, second fails with any file. That means all validations used don't work (except size, which I haven't tested). It worked fine previously with Rails 5.2 outside of the test environment

**Comment by igorkasyanchuk** [comment]
@falseresync try to pull gem and contribute and fix the issue, this is really difficult to find time. Gem has specs so it's possible to do.

**Comment by falseresync** [comment]
Ok, after pulling the gem and experimenting with it, I found that the major problem were wrong specs. Gem doesn't purge the attachment if it is invalid, so `be_attached` is always truthy. After changing examples to:
```ruby
it 'should allow attaching a picture' do
  subject.avatar.attach(...)
  expect(subject).to be_valid
end
it 'should not allow attaching garbage' do
  subject.avatar.attach(...)
  expect(subject).not_to be_valid
end
``` 
It partially worked. Now it doesn't allow correct image, aspect ratio and dimension validators reject it

**Comment by igorkasyanchuk** [comment]
@falseresync so ... what is expected?

**Comment by falseresync** [comment]
I tested it, it seems like the image being parsed in a wrong way. I expect it to allow correct image that should satisfy the conditions, but it is not because of these two validators. Honestly, I have no idea where the problem is

**Comment by igorkasyanchuk** [comment]
@falseresync try to make a PR with a test with a problem, describe the problem and maybe later me or someone could take a look

**Comment by falseresync** [comment]
Oh! No need for that. I found the issue. I have no ImageMagick installed and RSpec blocks all of the messages from the gem. Thank you :)
