### ISSUE TITLE
Not valid file not purged from database

### ISSUE THREAD

**Issue by frobert** [igorkasyanchuk/active_storage_validations#41]
The validation message works but the not valid file is still in database, should be purged/removed after it is not valid.

Any advice?

**Comment by igorkasyanchuk** [comment]
version of Rails? if 5.2 this is known issue. In Rails 6 it's fixed. This is internal bug in active storage

**Comment by frobert** [comment]
It is Rails 6

**Comment by igorkasyanchuk** [comment]
oh, maybe it was not fixed, original issue was here: https://github.com/rails/rails/issues/33741

**Comment by frobert** [comment]
:/ any ideas on a workaround?

**Comment by igorkasyanchuk** [comment]
no ideas. maybe in the controller if validation failed you need to clean up invalid files. Basically iterate over files and purge/delete them.
