### ISSUE TITLE
Limit validator not working for rails 6

### ISSUE THREAD

**Issue by UICJohn** [igorkasyanchuk/active_storage_validations#42]
The limit validation doesn't work for rails 6 active storage

The change of implementation of ActiveStorage::Attached::Many#attach bellow cause duplicate attachables which break the limit validation.

```
    def attach(*attachables)
-      attachables.flatten.collect do |attachable|
-        if record.new_record?
-          attachments.build(record: record, blob: create_blob_from(attachable))
-        else
-          attachments.create!(record: record, blob: create_blob_from(attachable))
-        end
+      if record.persisted? && !record.changed?
+        record.update(name => blobs + attachables.flatten)
+      else
+        record.public_send("#{name}=", blobs + attachables.flatten)
       end
     end
```

**Comment by igorkasyanchuk** [comment]
Can you make a fix and PR?

**Comment by UICJohn** [comment]
Sure
Just wanna confirm something. 
Before I making any changes, I modified the test for limit validations in 
`active_storage_validations_test.rb line 65`

`test 'validates number of files' do
    e = Project.new(title: 'Death Star')
    e.preview.attach(big_file)
    e.small_file.attach(dummy_file)
    e.attachment.attach(pdf_file)
    e.documents.attach(pdf_file)
+    p e.documents.attachments.count
    e.documents.attach(pdf_file)
    e.documents.attach(pdf_file)
    e.documents.attach(pdf_file)
    assert !e.valid?
    assert_equal e.errors.full_messages, ['Documents total number is out of range']
  end`

It prints out the attachments count is 0.  Is that expected？ or that should be fixed? no offence just wanna make sure I have the correct view.

**Comment by igorkasyanchuk** [comment]
pls try: active_storage_validations-0.8.5.gem
