### ISSUE TITLE
content_type validator doesn't quite work

### ISSUE THREAD

**Issue by connorshea** [igorkasyanchuk/active_storage_validations#43]
So I just discovered that the content type validation doesn't work quite right at the moment if you upload, e.g. a webp file with the name `image.png`.

To reproduce the issue:

- Create an attachment on a model where the attachment can only be a PNG.
```ruby
validates :avatar,
  attached: false,
  content_type: ['image/png']
```

- Find and download a webp file (see https://developers.google.com/speed/webp/gallery1 for some examples)
- Upload the webp file to your Rails app
- See that it fails.
- Rename it to `whatever.png`
- Upload the file again.
- See that it gets uploaded successfully.

You can reproduce this with the avatar uploader [my Rails app](https://github.com/connorshea/VideoGameList), though it might be overkill to set it up just for this :)

Oddly, ActiveStorage does seem to analyze the image properly. as it ends up having a content_type of `image/webp` in the `active_storage_blobs` table. I'm not sure if it briefly has an incorrect content type immediately after upload or something?

This caused a problem with my application because ImageMagick can't handle webp files when producing variants, so it was causing errors.

Versions:

active_storage_validations: 0.8.3
Rails: 6.0.0

**Comment by igorkasyanchuk** [comment]
Not sure if the issue exists: https://github.com/igorkasyanchuk/active_storage_validations/commit/d7020c06af58f5ab94aead42d46fc31553c97faf

but here is the test. If you can make test fail and than fix it would be great

**Comment by connorshea** [comment]
Do the tests run on a specific version of Rails?

**Comment by igorkasyanchuk** [comment]
https://travis-ci.org/igorkasyanchuk/active_storage_validations/builds/613692053 5.2, 6.0

try to reproduce in your branch
