### ISSUE TITLE
Raise exception when ImageMagick not installed

### ISSUE THREAD

**Issue by romkaspb** [igorkasyanchuk/active_storage_validations#47]
Hey Igor, thanks for your gem.
When I try to add `dimension` validation and no ImageMagick installed, I'm getting error ActiveRecord validation error with text `Image is not a valid image`. It's expectedly but not obvious to have ImageMagick installed.

I think it's better to throw exception when user tries to use `dimension` validator. What do you think about it? I can create PR if nesessary. 

Thanks!

**Comment by igorkasyanchuk** [comment]
Hi, in readme there is instruction about it: https://github.com/igorkasyanchuk/active_storage_validations#installation
