### ISSUE TITLE
Metadata validation fails when config.active_storage.replace_on_assign_to_many = false

### ISSUE THREAD

**Issue by sarahstrong** [igorkasyanchuk/active_storage_validations#58]
Using Rails 6
Set config.active_storage.replace_on_assign_to_many = false to append to blobs list on update instead of replacing, see: https://edgeguides.rubyonrails.org/6_0_release_notes.html
On a record which has_many_attached blobs, set metadata validations like dimension: { width: { min: 200 }, height: { min: 200 } }
Attach one or more images to a record. This succeeds.
Now, attach one or more images to the record again. This fails with:

RuntimeError in Controller#update
Something wrong with params.

`active_storage_validations (0.8.7) lib/active_storage_validations/metadata.rb:67:in `read_file_path'
active_storage_validations (0.8.7) lib/active_storage_validations/metadata.rb:37:in `read_image'
active_storage_validations (0.8.7) lib/active_storage_validations/metadata.rb:10:in `metadata'
active_storage_validations (0.8.7) lib/active_storage_validations/dimension_validator.rb:46:in `block in validate_each'
active_storage_validations (0.8.7) lib/active_storage_validations/dimension_validator.rb:45:in `each'
active_storage_validations (0.8.7) lib/active_storage_validations/dimension_validator.rb:45:in `validate_each'
activemodel (6.0.2.1) lib/active_model/validator.rb:152:in `block in validate'
activemodel (6.0.2.1) lib/active_model/validator.rb:149:in `each'
activemodel (6.0.2.1) lib/active_model/validator.rb:149:in `validate'
...`

Params:

`"images"=>
    [#<ActionDispatch::Http::UploadedFile:0x00007fed67101308
      @content_type="image/jpeg",
      @headers="Content-Disposition: form-data; name=\"object[images][]\"; filename=\"filename.jpg\"\r\n" + "Content-Type: image/jpeg\r\n",
      @original_filename="filename.jpg",
      @tempfile=#<File:/tmp/RackMultipart20200127-18612-ox8p5.jpg>>],`

**Comment by igorkasyanchuk** [comment]
@sarahstrong can you try to pull repo and try to make a fix?

**Comment by reckerswartz** [comment]
cc @igorkasyanchuk please close this issue.
