### ISSUE TITLE
Content type validation should handle regex expression

### ISSUE THREAD

**Issue by GBH** [igorkasyanchuk/active_storage_validations#6]
`validates :image, content_type: /\Aimage\/.*\z/` Should  be a valid expression

**Comment by ivanelrey** [comment]
@igorkasyanchuk what you think about this issue? Should this be implemented?

**Comment by igorkasyanchuk** [comment]
Probably, if you want to implement it could be useful for some people.

**Comment by igorkasyanchuk** [comment]
Implementerd
