### ISSUE TITLE
uninitialized constant ModuleX::ModuleY::ModuleZ::AttachedValidator

### ISSUE THREAD

**Issue by JohnSmall** [igorkasyanchuk/active_storage_validations#69]
This is similar to
[issue 15](https://github.com/igorkasyanchuk/active_storage_validations/issues/15), but the context is sufficiently different to make a new issue.

Using Rails 5.2.3 with Ruby2.5.5. 

This is a project I've inherited and it's old convoluted code. I'm moving from using Paperclip to ActiveStorage and trying to use active_storage_validations. 

In part of the project we define an `acts_as_image_upload` method and then use that elsewhere on ActiveRecord models that need to have an image asset attached. The definition sits in an internal gem (actually a modified engine) which in included in the Gemfile for various projects inside the company. 

In other words I'm not using `active_storage_validations` directly in models, but indirectly via an `acts_as_x` method. But it's not working.

I've defined this ;

     # unnecessary code removed
     module SomeDummyName
      def acts_as_image_upload
        has_one_attached :attachment
        validates :attachment, attached: true
     end 
     # unnecessary code removed
     ActiveRecord::Base.extend(SomeDummyName)
     # unnecessary code removed

When I try to use it in a model which is namespaced as  `ModuleX::ModuleY::ModuleZ::ModelClass` then I get this error;- 

   uninitialized constant ModuleX::ModuleY::ModuleZ::AttachedValidator

So it's clear that the validator isn't being added to the model in this case. 

Obviously by putting a `require` and `include` in the correct place I should be able to get this working. How can I do it?

**Comment by JohnSmall** [comment]
Good idea but..

The examples in the documentation on ActiveSupport::Concern don't match the pattern for using your gem.

In the examples  in the documentation a module is included inside another module so it's clear where you have to put `extend ActiveSupport::Concern`. I've used concerns elsewhere in ActiveRecords and never had a problem.

But your code includes itself into ActiveSupport when ActiveRecord is loaded. So I can't work out where I'd put  `extend ActiveSupport::Concern`. 

As a guess I tried 

     require 'active_support/concern'
     # unnecessary code removed
      module X
        module Y
          module SomeDummyName
             include ActiveSupport::Concern 
               def acts_as_image_upload
                  has_one_attached :attachment
                  validates :attachment, attached: true
               end 
             # unnecessary code removed
             
           end
        end
      end
      ActiveRecord::Base.extend(X::Y::SomeDummyName)

It didn't work, and I didn't expect it to work, because I'm not adding `include ActiveSupport::Concern` into your code.

The objective is to stick as close as possible to the legacy code I've inherited and that simply uses  `acts_as_image_upload` inside the ActiveRecord models that need it. So I don't want to change the code in those models if it can be avoided.

Thanks for your help

**Comment by JohnSmall** [comment]
Solved it!!!

My `acts_as_image_upload` was defined in a gem which we use internally to share between different projects. I'd included `active_storage_validations` in the dependencies for that gem. But that meant the dependencies were loaded in the wrong order.

All I had to do was add `active_storage_validations` into the Gemfile for the top level project, right after `rails` and it now works.

**Comment by igorkasyanchuk** [comment]
Wonderful 👍
