### ISSUE TITLE
Error AttachedValidator

### ISSUE THREAD

**Issue by dwthien** [igorkasyanchuk/active_storage_validations#70]
I have the issue when I build the class inside the module, look at the image, It will work if I comment validation code. Can you help me resolve this issue?
Rails 6.0.2.1 

![image](https://user-images.githubusercontent.com/25741737/80008325-cb3d5300-84f1-11ea-9e7f-f02d847d2ffa.png)
![image](https://user-images.githubusercontent.com/25741737/80008347-d42e2480-84f1-11ea-8a00-19dafc089e2c.png)

**Comment by igorkasyanchuk** [comment]
What was the solution?

**Comment by dwthien** [comment]
> What was the solution?

Hi @igorkasyanchuk , 
Sorry about this, I installed gem but I didn't restart rails console, so didn't load the gem.

Thank you for your support.
