### ISSUE TITLE
There's a way to save a record with no attachment even with an attachment presence validation (using Trestle)

### ISSUE THREAD

**Issue by gitjul** [igorkasyanchuk/active_storage_validations#80]
I ran into an issue when using active_storage_validations with Trestle (https://github.com/TrestleAdmin/trestle/trestle-active_storage) and with trestle-active_storage (https://github.com/richardvenneman/trestle-active_storage, wrote about the issue here: https://github.com/richardvenneman/trestle-active_storage/issues/23) and I'm not sure which of the gems possibly "owns" the issue, so forgive me if I'm wrong to open this issue here.

I found that there's a way to save a record with no attachments even with a presence validation. The validation works if you're trying to save a newly added record and adding attachments for the first time (or rather not adding any and wanting to save the record). But when you successfully save a record, and then delete all the attachments and save, it's successfully saved, even though the record is invalid (and you can check that in rails console ofc with `the_saved_record.valid?`, which is `false`).

I haven't found an issue anywhere, could you tell me if this is something you know about if you know a fix/workaround? Also let me know if this is not the right place for this issue. Thx!

PS Huge thank you for this gem <3 💎 

PS thanks for the gem! 💎

**Comment by igorkasyanchuk** [comment]
@gitjul if possible, please replicate with test inside test/dummy app in this gem

if you can make a test which fails it would be a nice start point to fix this issue

sorry but I need support from you too :)

**Comment by gitjul** [comment]
@igorkasyanchuk sure, no time now but I'll try when I have some

**Comment by Mth0158** [comment]
Hi @gitjul 
Long long time, do you still have this issue? If not I will close this issue for cleaning up our issue tracker
