### ISSUE TITLE
Specs not recognising the on method (thus can't scope validations to update in specs)

### ISSUE THREAD

**Issue by ernest4** [igorkasyanchuk/active_storage_validations#87]
Hi :) great work on the gem!

I have a validation that I only want to run on update. The validation does run on update as I expect, however the specs don't look like they recognise the **on** method. So basically can't use the specs to check for validation on update, only on create (default).

<img width="1053" alt="Screenshot 2020-10-01 at 13 26 02" src="https://user-images.githubusercontent.com/35740142/94808969-d625d900-03e9-11eb-8041-0cff5ddd15f9.png">

<img width="1288" alt="Screenshot 2020-10-01 at 13 25 52" src="https://user-images.githubusercontent.com/35740142/94808965-d45c1580-03e9-11eb-871e-89fffbae9c62.png">

I'm surprised no one brought this up yet as I'd imagine this would be fairly common. Unless there's some work around for this? But I haven't spotted any?

If there's a workaround, could you please let me know. Otherwise, could this be added to specs :)

Thanks.

**Comment by igorkasyanchuk** [comment]
I guess, matcher in the gem doesn't support this option so I think the best is to fork a gem and make a fix 👍

**Comment by Mth0158** [comment]
Hi @ernest4,
Thanks for bringing it up,
We recently had a discussion on adding a `#on `method on our matchers in order to perform the test you are mentioning in #215.
I am therefore closing your ticket so we don't have a duplicate.
Feel free to drop a PR on #215 if you want to contribute 🙌
