### ISSUE TITLE
TypeError (no implicit conversion of StringIO into String) - Decoding base64 file

### ISSUE THREAD

**Issue by dinhngochien** [igorkasyanchuk/active_storage_validations#89]
Hi, first of all, thank you for your hard work in building a fantastic gem.
I got an issue with validating file, when I was trying to save the decoded file the error occurred:
`TypeError (no implicit conversion of StringIO into String)`
Here is my controller where I save the file:
```ruby
   @video_template.video.attach(
      io: StringIO.new(Base64.decode64(params[:video].split(',')[1])),
      filename: "video#{Time.now.strftime('%Y%m%d%H%M%S')}.mp4"
    )
    @video_template.thumbnail.attach(
      io: StringIO.new(Base64.decode64(params[:thumbnail].split(',')[1])),
      filename: "thumbnail#{Time.now.strftime('%Y%m%d%H%M%S')}.jpg"
    )

    if @video_template.save # error comes from here
      render json: @video_template, serializer: VideoTemplateSerializer
    end
```
In my model, there is my validation:
```ruby
  has_one_attached :video
  has_one_attached :thumbnail

  validates :video, attached: true,
                    size: { less_than: 10.megabytes , message: I18n.t('video_size_too_big') },
                    content_type: { in: 'video/mp4', message: I18n.t('video_type_wrong') }
  validates :thumbnail, attached: true,
                        size: { less_than: 1.megabyte, message: I18n.t('video_thumbnail_too_big') },
                        content_type: { in: ['image/jpg', 'image/jpeg'], message: I18n.t('video_thumbnail_type_wrong')},
                        dimension: { width: { min: 0, max: 240 },
                                     height: { min: 0, max: 240 }, message: I18n.t('video_thumbnail_wrong_demension') }
```
If I comment out the validates, then I can save successfully. I'm not sure that the root cause of this error comes from active_storage_validations or not, but the record can save normally if it has no validation made me think about this.
I'm using version: 0.9.0
ruby '2.7.1'
rails '6.0.3'

**Comment by reckerswartz** [comment]
@dinhngochien in examples io using a file input
```ruby
@message.image.attach(io: File.open('/path/to/file'), filename: 'file.pdf')
```
can you try using it?

**Comment by igorkasyanchuk** [comment]
He is receiving the file as Base64 string and needs to save first content to the tempfile, which is not convenient.
But I guess without file on disk validations for size, resolution will not work, just my guess.

**Comment by reckerswartz** [comment]
Yes, there might be a way to convert the Base64 string into the File input string without saving on disk.

**Comment by dinhngochien** [comment]
Thank you so much for supporting guys, I finally found a way to save the file without affecting the validation. I will close the issue.

**Comment by aebejer** [comment]
For others that run into this problem, you can do something like this in rails 6:
```
    # read image data
    image_data = record.attachment_changes[:thumbnail].attachable[:io].string
    image = MiniMagick::Image.read(image_data)
    image_aspect_ratio = image.width/image.height.to_f
```

**Comment by colinchan15** [comment]
@dinhngochien I'm running into the same issue. What was your solution to this issue?

**Comment by kwent** [comment]
Hi, i'm seeing the same error with the snippet of code below. Works well if i removed the `aspect_ratio: :square` validation

```ruby
    user_avatar = "https://img.favpng.com/17/19/1/business-google-account-organization-service-png-favpng-sUuKmS4aDNRzxDKx8kJciXdFp.jpg"
    filename = File.basename(URI.parse(user_avatar).path)
    file = URI.parse(user_avatar).open
    @user.avatar.attach(io: file, filename: filename) # need to be square ratio
```

Regareds

**Comment by igorkasyanchuk** [comment]
@kwent I think the best is if you can clone the gem repo, connect it locally, and but binding.pry inside gem and run your code. If you can find exact error and make a PR it would be great and I'll merge it
