### ISSUE TITLE
ActiveAdmin and active_storage_validations

### ISSUE THREAD

**Issue by PSM8493** [igorkasyanchuk/active_storage_validations#95]
This Gem is great. i'm using it for a front end form which is perfect.

I'm also using it for the Admin part of my App using activeadmin gem.

I get validation error message in ActiveAdmin but it saves the file and ignores the validations

`validates :images, content_type: ['image/png', 'image/jpg', 'image/jpeg'], limit: { min: 1, max: 2,  message: 'You are allowed a maximum of 2 attachments' }, size: { less_than: 200.kilobytes , message: 'The attachment(s) must be less than 200kb' }`

Would be great if you could give some pointers. Really stuck :-(
This is a similar issue with another gem 

https://github.com/aki77/activestorage-validator/issues/1

Thank you

**Comment by igorkasyanchuk** [comment]
Sorry, can't help now with this issue. I'm not a fan of ActiveAdmin and never used it. Maybe you can contribute to it
